const categories = {
    category_web: "Web Development",
    category_app: "App Development",
    category_ai: "Artificial Intelligence",
    category_business: "Business Intelligence",
    category_editing: "Video Editing",
    category_media: "Social Media",
}

export const course_data = [
    {
        title: "HTML / CSS From Zero to Hero",
        auther: "Shiva Pandey",
        src: "/images/course/html-css.png",
        category: categories.category_web,
        rating: 4.8,
        price: "149/-",
        discount_price: "Free",
    },
    {
        title: "Advanced Javascript",
        auther: "Devendra Singh",
        src: "/images/course/javascript.jpg",
        category: categories.category_web,
        rating: 4.5,
        price: "99/-",
        discount_price: "Free",
    },
    {
        title: "Next Js / React Js Full course",
        auther: "Shiva Pandey",
        src: "/images/course/nextjs.png",
        category: categories.category_web,
        rating: 4.5,
        price: "199/-",
        discount_price: "Free",
    },
    {
        title: "Flutter App Development",
        auther: "Zaid Sayyed",
        src: "/images/course/flutter.jpeg",
        category: categories.category_app,
        rating: 4.8,
        price: "149/-",
        discount_price: "Free",
    },
    {
        title: "Kotlin Crash Course",
        auther: "Zaid Sayyed",
        src: "/images/course/kotlin.webp",
        category: categories.category_app,
        rating: 4.3,
        price: "99/-",
        discount_price: "Free",
    },
    {
        title: "Gen AI | ChatGPT",
        auther: "Sanskar Dubey",
        src: "/images/course/gen-ai.png",
        category: categories.category_ai,
        rating: 4.8,
        price: "199/-",
        discount_price: "Free",
    },
    {
        title: "AI / Machine Learning",
        auther: "Shiva Pandey",
        src: "/images/course/ai-ml.jpg",
        category: categories.category_ai,
        rating: 4.0,
        price: "99/-",
        discount_price: "Free",
    },
    {
        title: "Data Science and Analysis",
        auther: "Devendra Singh",
        src: "/images/course/data-science.png",
        category: categories.category_ai,
        rating: 4.5,
        price: "149/-",
        discount_price: "Free",
    },
    {
        title: "Video Editing",
        auther: "Safwan Khan",
        src: "/images/course/video-editing.png",
        category: categories.category_editing,
        rating: 4.6,
        price: "99/-",
        discount_price: "Free",
    },
    {
        title: "Photo Editing",
        auther: "Safwan Khan",
        src: "/images/course/photo-editing.jpg",
        category: categories.category_editing,
        rating: 4.4,
        price: "99/-",
        discount_price: "Free",
    },
    {
        title: "Social Media",
        auther: "Sanskar Dubey",
        src: "/images/course/social-media.png",
        category: categories.category_media,
        rating: 4.8,
        price: "149/-",
        discount_price: "Free",
    },
]
